### ISSUE TITLE
linter status doesn't update until save

### ISSUE THREAD

**Issue by ssfrr** [deprint/build-tools-cpp#20] opened 2015-07-01 22:14 UTC
After running a build, my linter status bar doesn't update with the results until I save the buffer. Is this an issue on build-tools-cpp or with Linter?

**Comment by ssfrr** [comment] 2015-07-02 16:31
Awesome, thanks for the quick response!

As of 2.0.6 it seems to update if the build fails, but if the build succeeds the errors and highlighting disappear but the status bar at the bottom still shows there are issues. Maybe this is a bug with Linter partially updating?

**Comment by deprint** [comment] 2015-07-05 17:50
I ran a few tests and it appears that there are issues on both sides. It'll be fixed with the next update (v3.0.0).

**Comment by deprint** [comment] 2015-07-13 22:51
I changed almost everything related to error highlighting and the bug magically disappeared. I don't know how (maybe Linter had bugs too) but I can't reproduce the issue so I guess it's fixed (?)

**Closed by deprint** 2015-07-13 22:51 UTC
Labels: bug
