### ISSUE TITLE
Auto-hide and/or keyboard shortcut to hide

### ISSUE THREAD

**Issue by ssfrr** [deprint/build-tools-cpp#22] opened 2015-07-02 18:15 UTC
Most of the time if my build succeeds I don't really need to see the output (or don't need to inspect it carefully anyways), so it would be great if the output window automatically disappeared after a couple seconds.

Barring that (or maybe in addition) it would be great to have a quick keyboard shortcut to hide the output window, or maybe change the existing `Show` command into a `Toggle`.

Thanks, your package is becoming a core part of my workflow, it's really awesome.

**Comment by deprint** [comment] 2015-07-13 22:46
The package's settings view now has a "Close console on success" option.
I also added a key binding for `build-tools:show` and the output window can be closed with `ESC`.

**Comment by ssfrr** [comment] 2015-07-13 22:53
Sounds great, I look forward to upgrading. Thanks!

**Comment by uraza** [comment] 2015-11-03 09:01
Hi @deprint 
I had some troubles making it work.
On my side, it turns out that the console only hides when the second console option ("Execute Queue in one tab") is unchecked.
Is it the expected behavior?

**Comment by deprint** [comment] 2015-11-03 10:16
Looks like a bug to me

**Comment by deprint** [comment] 2015-11-03 15:17
Fixed in `v4.0.4`.
Keep in mind, when you execute multiple commands in one tab and want to hide the output on success, `Execute Queue in one tab` and `Close on success` of the __last__ command are relevant.

**Closed by deprint** 2015-11-03 15:17 UTC
Labels: bug

**Comment by uraza** [comment] 2015-11-03 15:22
Thanks for the clarification and for the quick fix, this package is VERY helpful! :)
