### ISSUE TITLE
Can't install package.

### ISSUE THREAD

**Issue by mira13** [deprint/build-tools-cpp#51] opened 2015-12-08 08:24 UTC
Installing “build-tools@4.3.1” failed.

> pty.js@0.3.0 install C:\Users\Mira\AppData\Local\Temp\apm-install-dir-115118-7060-qsddnj\node_modules\build-tools\node_modules\pty.js
> node-gyp rebuild

C:\Users\Mira\AppData\Local\Temp\apm-install-dir-115118-7060-qsddnj\node_modules\build-tools\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\Mira\AppData\Local\atom\app-1.2.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Mira\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Mira\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Mira\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Mira\\.atom\\.apmrc" "install" "C:\\Users\\Mira\\AppData\\Local\\Temp\\d-115118-7060-mc9wq\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by deprint** [comment] 2015-12-08 08:53
Duplicate of #47

**Closed by deprint** 2015-12-08 08:53 UTC
